Lesson5
HEOcanuAHT/Eshop pull request #4
Opened 2024-10-23 10:21 UTC by HEOcanuAHT

DAL memmory, JSON
небольшой рефакторинг

2024-10-28 09:51 UTC, YakovGolev requested changes

2024-10-28 09:51 UTC, YakovGolev commented on .filenesting.json
ненужный файл

2024-10-28 09:51 UTC, YakovGolev commented on Core/CartItem.cs
> +        private CartItem(Product? product, Service? service, uint count = 1)
Чтобы обойти проблемы с десериализацией лучше использовать промежуточную сущность (класс) для сериализации и десериализации. Этот класс может содержать удобный для сериализатора контракт, а преобразование в нужный класс может производиться на уровне репозитория.

2024-10-28 09:51 UTC, YakovGolev commented on Core/IStoragedCatalog.cs
> +    public interface IStoragedCatalog
Неудачное название интерфейса. В данном случае это сущность которая имеет идентификатор (`IIdentityEntity` или что-то типа того), никакого прямого отношения к каталогу этот интерфейс не имеет.

2024-10-28 09:51 UTC, YakovGolev commented on Core/Product.cs
> +public class Product : SaleItem, IStoragedCatalog
Интерфейс, в данном случае, лучше реализовывать в базовом классе

2024-10-28 09:51 UTC, YakovGolev commented on Core/SaleItemType.cs
> +        Product,
Задай явно значения, удобнее потом будет

2024-10-28 09:51 UTC, YakovGolev commented on Eshop/ApplicationContext.cs
> +            _cart = JsonSerializer.Deserialize<Cart>(fs) ?? new();
Тут напрашивается репозиторий для корзины. Маркер, что детали работы с данными просочились в слой приложения

2024-10-28 09:51 UTC, YakovGolev commented on Eshop/Menu/Commands/OrderPayCommand.cs
> +            if (_paymentMethod is not IOrderPayment paymentMethod)
тут некорректная проверка _paymentMethod и так IOrderPayment, другое дело, что нужна проверка на null

2024-10-28 09:51 UTC, YakovGolev commented on Eshop/Menu/Commands/OrderPayCommand.cs
> +            IOrderPayment paymentMethod = userInput switch
Стратегия 👍

2024-10-28 09:51 UTC, YakovGolev commented on Eshop/ApplicationContext.cs
> +            _sp = sp;
Эта ссылка нигде не используется, она лишняя. Кроме того, если бы ты попробовал её использовать, то получил бы исключение, т.к. при выходе из этого конструктора у объекта sp будет вызван метод Dispose (конструкция using var ...), а поле _sp и переменная sp указывают на один и тот же объект.

2024-11-01 10:22 UTC, HEOcanuAHT commented on Core/CartItem.cs
> +        private CartItem(Product? product, Service? service, uint count = 1)
не пофиксил, так нехочется создавать отдельную сущность(( 
пусть так останется, всё равно в PG переехали))  вроде как через Анонимный тип можно прочитать чтобы не городить отдельных классов, встречал пример на просторах интернета.

2024-11-02 03:36 UTC, av-leschinskiy approved these changes
Не стал во всех местах писать - обычно используется проброс зависимостей через конструктор, вместо GetRequiredService, GetRequiredService - жестче связывает чем конструтор.

2024-11-02 03:36 UTC, av-leschinskiy commented on Eshop/Menu/OrdersPage.cs
> +            commands.Add(1, ServiceProvider.GetRequiredService<OrderPayCommand>());
Обычно мы прокидываем зависимости через конструктор: 

`public OrdersPage(Dictionary<int, IMenuCommand> commands, OrderPayCommand orderPayCommand) : base(commands)
{
    commands.Add(1, orderPayCommand);`
он по типу в параметрах поймет что ему нужно взять реализацию для OrderPayCommand из контейнера

2024-11-02 03:36 UTC, av-leschinskiy commented on Eshop/Menu/Commands/ShowCatalogCommand.cs
> +            var saleItemManager = serviceProvider.GetRequiredService<IRepository<T>>();
manager - это сущность которая занимается менеджментом - управлением обычно это какой-то класс маршрутизатор для плотной бизнесовой логики, здесь так можно и назвать saleItemRepository

2024-11-02 03:36 UTC, av-leschinskiy commented on Eshop/Menu/Commands/ShowCatalogCommand.cs
> +            var saleItemManager = serviceProvider.GetRequiredService<IRepository<T>>();
у тебя все поведение класса зависит от saleItemManager - его можно сделать приватным полем и прокидывать в конструкторе, чтобы не получать в ручную из сервис провайдера

2024-11-02 03:36 UTC, av-leschinskiy commented on Eshop/Menu/Commands/ShowCatalogChoiceCommand.cs
> +                { 1, sp.GetRequiredService<ShowCatalogCommand<Product>>() },
лучше через конструктор, см. другие комментарии.

2024-11-02 03:36 UTC, av-leschinskiy commented on Eshop.DataAccess/PGDataStorage/ServicePGDataStorage.cs
> +namespace Eshop.DataAccess.PGDataStorage
Странная штука, но в абревиатурах следует писать вот так PgDataStorage, т.е. не все буквы аббревиатуры писать с большой буквы, а придерживаться камел кейса даже для букв аббревиатуры

2024-11-02 03:36 UTC, av-leschinskiy commented on Core/IRepository.cs
> +    public interface IRepository<T> where T : IStoraged
IStoraged - мутное имя, судя по контракту он IIdentifable или что-то такое

2024-11-06 00:15 UTC, HEOcanuAHT commented on Core/IRepository.cs
> +    public interface IRepository<T> where T : IStoraged
идея была ограничить тип дженерика репозитория чем то что может храниться, типа Хранимое и что имеет списочное поведение как справочник в 1С (первоначально обозвал IStoragedCatalog), с реквизитами по умолчанию аля ИД.. Но что то прям не зашла идея никому)) избавился от него..

2024-11-06 23:03 UTC, merged